from playwright.sync_api import Playwright, sync_playwright


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://app.genzopss.com/login")
    page.get_by_role("button", name="Standard Civil Works BoQ v1").click()
    page.get_by_role("button", name="Item").click()
    page.get_by_role("textbox", name="Description *").click()
    page.get_by_role("textbox", name="Description *").fill("Wall Foundation")
    page.get_by_role("combobox").select_option("183056e5-23ca-46b3-888b-f9416c15ae30")
    page.get_by_role("textbox", name="Unit (cum, sqm, kg…)").click()
    page.get_by_role("textbox", name="Unit (cum, sqm, kg…)").fill("KG")
    page.get_by_placeholder("Quantity *").click()
    page.get_by_placeholder("Quantity *").fill("567")
    page.get_by_placeholder("Rate (₹) *").click()
    page.get_by_placeholder("Rate (₹) *").fill("345")
    page.locator("form").get_by_role("button", name="Item").click()
    page.get_by_role("button", name="Rate Analysis").nth(1).click()
    page.get_by_role("textbox", name="Component description").click()
    page.get_by_role("textbox", name="Component description").fill("Item")
    page.get_by_role("textbox").nth(2).click()
    page.get_by_role("textbox").nth(2).fill("KG")
    page.get_by_role("spinbutton").nth(1).click()
    page.get_by_role("spinbutton").nth(1).fill("56")
    page.get_by_role("spinbutton").nth(2).click()
    page.get_by_role("spinbutton").nth(2).fill("351")
    page.get_by_role("button", name="Add component").click()
    page.get_by_role("combobox").nth(1).select_option("labour")
    page.get_by_role("textbox", name="Component description").nth(1).click()
    page.get_by_role("textbox", name="Component description").nth(1).fill("Labour for Foundation")
    page.get_by_role("textbox").nth(4).click()
    page.get_by_role("textbox").nth(4).fill("Day")
    page.get_by_role("spinbutton").nth(3).click()
    page.get_by_role("spinbutton").nth(3).fill("6")
    page.get_by_role("spinbutton").nth(4).click()
    page.get_by_role("spinbutton").nth(4).fill("600")
    page.get_by_role("button", name="Add component").click()
    page.get_by_role("combobox").nth(2).select_option("equipment")
    page.get_by_role("textbox", name="Component description").nth(2).click()
    page.get_by_role("textbox", name="Component description").nth(2).fill("JCB")
    page.locator("div:nth-child(4) > input:nth-child(3)").click()
    page.locator("div:nth-child(4) > input:nth-child(3)").fill("N/A")
    page.get_by_role("spinbutton").nth(5).click()
    page.get_by_role("spinbutton").nth(5).fill("23")
    page.locator("div:nth-child(4) > input:nth-child(5)").click()
    page.locator("div:nth-child(4) > input:nth-child(5)").fill("450")
    page.get_by_role("button", name="Apply to BoQ rate").click()
    page.get_by_role("button", name="BoQ").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
